   # 4.8 Task - Aggregating Variables

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df_orders_products_merged = pd.read_pickle(r'/Users/elenasharavara/Documents/08-2023 Instacart Grocery Basket Analysis /02 Data/Prepared Data/orders_products_merged.pkl')

In [3]:
path = '/Users/elenasharavara/Documents/08-2023 Instacart Grocery Basket Analysis /02 Data/Prepared Data'

In [4]:
df_orders_products_merged =  pd.read_pickle(os.path.join(path,'orders_products_merged.pkl'))

In [6]:
df = df_orders_products_merged

In [7]:
df.shape

(32434212, 17)

In [9]:
df.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0.1_y,product_name,aisle_id,department_id,prices,_merge,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,10,New customer
1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,10,New customer
8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,10,New customer
9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer

In [10]:
df.columns

Index(['order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'Unnamed: 0.1_y', 'product_name',
       'aisle_id', 'department_id', 'prices', '_merge', 'max_order',
       'loyalty_flag'],
      dtype='object')

In [12]:
# Group by "product_name" 
df.groupby('product_name')

In [13]:
# Split the data into groups by "department_id" and then calculate the mean for each "order_number" column
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457687
2                17.277920
3                17.179756
4                17.811403
5                15.213779
6                16.439806
7                17.225773
8                15.340520
9                15.895474
10               20.197148
11               16.170828
12               15.887622
13               16.583304
14               16.757377
15               16.165037
16               17.663250
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

##  Create loyalty flag for existing customers.

In [21]:
# Check the data grouping for accuracy
pd.options.display.max_rows = None

In [15]:
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0.1_y,product_name,aisle_id,department_id,prices,_merge,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,10,New customer
1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,10,New customer
8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,10,New customer
9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer
10,2968173,15,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,both,22,Regular customer
11,1870022,15,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,both,22,Regular customer
12,1911383,15,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer
13,2715276,15,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer
14,487368,15,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer
15,2293453,19,2,5,14,6.0,196,3,0,195,Soda,77,7,9.0,both,9,New customer
16,1973799,19,5,6,12,8.0,196,15,1,195,Soda,77,7,9.0,both,9,New customer
17,532817,19,7,4,17,6.0,196,1,1,195,Soda,77,7,9.0,both,9,New customer
18,1573906,21,10,3,10,6.0,196,2,0,195,Soda,77,7,9.0,both,33,Regular customer
19,1593000,31,10,3,8,7.0,196,17,0,195,Soda,77,7,9.0,both,20,Regular customer
20,2231262,31,17,3,11,8.0,196,14,1,195,Soda,77,7,9.0,both,20,Regular customer
21,2580647,43,6,4,16,4.0,196,9,0,195,Soda,77,7,9.0,both,11,Regular customer
22,2187180,43,9,4,12,3.0,196,1,1,195,Soda,77,7,9.0,both,11,Regular customer
23,2497897,52,1,1,9,NaN,196,4,0,195,Soda,77,7,9.0,both,27,Regular customer
24,1318871,52,2,1,10,7.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer
25,1261384,52,3,1,10,7.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer
26,580568,52,5,2,10,8.0,196,6,1,195,Soda,77,7,9.0,both,27,Regular customer
27,2428073,52,7,2,7,8.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer
28,342306,52,9,1,11,7.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer
29,1520353,52,10,2,10,8.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer
30,2542086,52,11,2,9,7.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer
31,944694,52,12,1,16,6.0,196,7,1,195,Soda,77,7,9.0,both,27,Regular customer
32,1268191,52,15,2,11,8.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer
33,1122089,52,17,2,10,6.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer
34,1498922,52,18,2,10,14.0,196,6,1,195,Soda,77,7,9.0,both,27,Regular customer
35,180919,52,19,3,8,8.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer
36,2695875,52,21,5,10,30.0,196,1,1,195,Soda,77,7,9.0,both,27,Regular customer
37,3205960,67,1,3,11,NaN,196,1,0,195,Soda,77,7,9.0,both,24,Regular customer
38,970922,67,2,1,15,5.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer
39,596585,67,3,1,13,7.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer
40,2037087,67,4,2,9,8.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
41,2474111,67,5,3,14,8.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer
42,1568481,67,6,3,12,7.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer
43,2048527,67,8,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
44,2389031,67,9,2,14,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
45,2378562,67,10,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
46,1515698,67,11,1,11,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
47,1928050,67,12,2,12,8.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
48,1949274,67,13,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
49,551869,67,14,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
50,768572,67,16,4,10,9.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
51,150528,67,18,5,16,4.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
52,29758,67,19,0,14,9.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer
53,1558976,67,21,1,9,5.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer
54,863974,67,22,1,11,14.0,196,3,1,195,Soda,77,7,9.0,both,24,Regular customer
55,2308399,67,23,1,14,14.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer
56,2759128,81,3,1,9,14.0,196,2,0,195,Soda,77,7,9.0,both,7,New customer
57,1812985,81,5,2,20,30.0,196,1,1,195,Soda,77,7,9.0,both,7,New customer
58,1889835,82,1,3,15,NaN,196,6,0,195,Soda,77,7,9.0,both,19,Regular customer
59,499460,82,3,5,10,5.0,196,2,1,195,Soda,77,7,9.0,both,19,Regular customer
60,2728456,82,4,0,11,16.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer
61,2653743,82,6,4,9,13.0,196,5,1,195,Soda,77,7,9.0,both,19,Regular customer
62,1358880,82,9,1,10,30.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer
63,343588,82,10,2,11,1.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer
64,3034663,82,15,2,11,12.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer
65,147262,82,18,1,13,7.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer
66,3144004,82,19,2,15,8.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer
67,2126069,98,3,0,9,25.0,196,7,0,195,Soda,77,7,9.0,both,14,Regular customer
68,2210120,98,7,5,14,5.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer
69,681011,98,9,3,9,30.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer
70,2846344,98,11,4,13,15.0,196,2,1,195,Soda,77,7,9.0,both,14,Regular customer
71,747431,98,12,6,13,30.0,196,4,1,195,Soda,77,7,9.0,both,14,Regular customer
72,2383054,98,13,4,11,30.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer
73,1993729,98,14,5,8,8.0,196,2,1,195,Soda,77,7,9.0,both,14,Regular customer
74,1403849,109,3,3,17,9.0,196,5,0,195,Soda,77,7,9.0,both,6,New customer
75,520620,120,1,3,11,NaN,196,2,0,195,Soda,77,7,9.0,both,3,New customer
76,3273029,120,3,2,8,19.0,196,2,1,195,Soda,77,7,9.0,both,3,New customer
77,1861943,185,2,1,12,25.0,196,10,0,195,Soda,77,7,9.0,both,6,New customer
78,2040988,195,1,1,14,NaN,196,2,0,195,Soda,77,7,9.0,both,58,Loyal customer
79,1680569,195,8,1,9,4.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
80,276171,195,19,5,11,3.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
81,2744976,195,22,5,10,7.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
82,2781919,195,25,1,14,4.0,196,1,1,195,Soda,77,7,9.0,both,58,Loyal customer
83,1738718,195,31,2,8,4.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
84,3058369,195,34,3,10,6.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
85,1485596,195,37,2,15,0.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
86,417035,195,40,3,16,2.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
87,1615297,195,47,5,10,2.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer
88,1765587,195,52,3,12,2.0,196,3,1,195,Soda,77,7,9.0,both,58,Loyal customer
89,745908,195,57,4,11,3.0,196,3,1,195,Soda,77,7,9.0,both,58,Loyal customer
90,2505656,222,17,2,12,1.0,196,2,0,195,Soda,77,7,9.0,both,70,Loyal customer
91,3268370,222,38,5,15,1.0,196,6,1,195,Soda,77,7,9.0,both,70,Loyal customer
92,2016711,290,9,5,19,6.0,196,8,0,195,Soda,77,7,9.0,both,51,Loyal customer
93,2706088,290,28,6,10,7.0,196,16,1,195,Soda,77,7,9.0,both,51,Loyal customer
94,1952286,331,6,5,16,30.0,196,8,0,195,Soda,77,7,9.0,both,8,New customer
95,3226575,360,1,5,12,NaN,196,1,0,195,Soda,77,7,9.0,both,3,New customer
96,1469869,377,3,5,17,3.0,196,9,0,195,Soda,77,7,9.0,both,3,New customer
97,1927023,387,2,4,10,22.0,196,3,0,195,Soda,77,7,9.0,both,8,New customer
98,858092,420,4,1,19,30.0,196,2,0,195,Soda,77,7,9.0,both,22,Regular customer
99,119314,420,5,3,19,16.0,196,2,1,195,Soda,77,7,9.0,both,22,Regular customer

In [17]:
# Create flags to assign "loyalty" labels to user ID based on max order value
df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [18]:
df.loc[(df['max_order'] <= 40) & (df['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [19]:
df.loc[df['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [20]:
# Check frequencies of loyalty flags for accuracy
df['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: loyalty_flag, dtype: int64

## Find the mean of product prices by loyalty group.

In [23]:
# Group by "prices" 
df.groupby('prices')

In [24]:
# Split the data into groups by "loyalty_flag" and then calculate the mean for each "prices" column
df.groupby('loyalty_flag').agg({'prices': ['mean']})

                     prices
                       mean
loyalty_flag
Loyal customer    10.388747
New customer      13.294370
Regular customer  12.496203

## Create spending flag for each user based on average price of products across orders

In [26]:
# Group data by "user_id" column, generate mean product price for each user, create "mean_price" for aggregation results
df['mean_price'] = df.groupby(['user_id'])['prices'].transform(np.mean)

In [27]:
# Check grouping
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0.1_y,product_name,aisle_id,department_id,prices,_merge,max_order,loyalty_flag,mean_price
0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797
10,2968173,15,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,both,22,Regular customer,3.980556
11,1870022,15,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556
12,1911383,15,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556
13,2715276,15,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556
14,487368,15,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556
15,2293453,19,2,5,14,6.0,196,3,0,195,Soda,77,7,9.0,both,9,New customer,8.372059
16,1973799,19,5,6,12,8.0,196,15,1,195,Soda,77,7,9.0,both,9,New customer,8.372059
17,532817,19,7,4,17,6.0,196,1,1,195,Soda,77,7,9.0,both,9,New customer,8.372059
18,1573906,21,10,3,10,6.0,196,2,0,195,Soda,77,7,9.0,both,33,Regular customer,7.012683
19,1593000,31,10,3,8,7.0,196,17,0,195,Soda,77,7,9.0,both,20,Regular customer,8.137793
20,2231262,31,17,3,11,8.0,196,14,1,195,Soda,77,7,9.0,both,20,Regular customer,8.137793
21,2580647,43,6,4,16,4.0,196,9,0,195,Soda,77,7,9.0,both,11,Regular customer,7.444898
22,2187180,43,9,4,12,3.0,196,1,1,195,Soda,77,7,9.0,both,11,Regular customer,7.444898
23,2497897,52,1,1,9,NaN,196,4,0,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
24,1318871,52,2,1,10,7.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
25,1261384,52,3,1,10,7.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
26,580568,52,5,2,10,8.0,196,6,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
27,2428073,52,7,2,7,8.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
28,342306,52,9,1,11,7.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
29,1520353,52,10,2,10,8.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
30,2542086,52,11,2,9,7.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
31,944694,52,12,1,16,6.0,196,7,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
32,1268191,52,15,2,11,8.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
33,1122089,52,17,2,10,6.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
34,1498922,52,18,2,10,14.0,196,6,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
35,180919,52,19,3,8,8.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
36,2695875,52,21,5,10,30.0,196,1,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876
37,3205960,67,1,3,11,NaN,196,1,0,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
38,970922,67,2,1,15,5.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
39,596585,67,3,1,13,7.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
40,2037087,67,4,2,9,8.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
41,2474111,67,5,3,14,8.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
42,1568481,67,6,3,12,7.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
43,2048527,67,8,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
44,2389031,67,9,2,14,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
45,2378562,67,10,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
46,1515698,67,11,1,11,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
47,1928050,67,12,2,12,8.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
48,1949274,67,13,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
49,551869,67,14,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
50,768572,67,16,4,10,9.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
51,150528,67,18,5,16,4.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
52,29758,67,19,0,14,9.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
53,1558976,67,21,1,9,5.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
54,863974,67,22,1,11,14.0,196,3,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
55,2308399,67,23,1,14,14.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790
56,2759128,81,3,1,9,14.0,196,2,0,195,Soda,77,7,9.0,both,7,New customer,8.262963
57,1812985,81,5,2,20,30.0,196,1,1,195,Soda,77,7,9.0,both,7,New customer,8.262963
58,1889835,82,1,3,15,NaN,196,6,0,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
59,499460,82,3,5,10,5.0,196,2,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
60,2728456,82,4,0,11,16.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
61,2653743,82,6,4,9,13.0,196,5,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
62,1358880,82,9,1,10,30.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
63,343588,82,10,2,11,1.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
64,3034663,82,15,2,11,12.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
65,147262,82,18,1,13,7.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
66,3144004,82,19,2,15,8.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221
67,2126069,98,3,0,9,25.0,196,7,0,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
68,2210120,98,7,5,14,5.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
69,681011,98,9,3,9,30.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
70,2846344,98,11,4,13,15.0,196,2,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
71,747431,98,12,6,13,30.0,196,4,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
72,2383054,98,13,4,11,30.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
73,1993729,98,14,5,8,8.0,196,2,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000
74,1403849,109,3,3,17,9.0,196,5,0,195,Soda,77,7,9.0,both,6,New customer,5.850725
75,520620,120,1,3,11,NaN,196,2,0,195,Soda,77,7,9.0,both,3,New customer,9.385714
76,3273029,120,3,2,8,19.0,196,2,1,195,Soda,77,7,9.0,both,3,New customer,9.385714
77,1861943,185,2,1,12,25.0,196,10,0,195,Soda,77,7,9.0,both,6,New customer,7.715000
78,2040988,195,1,1,14,NaN,196,2,0,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
79,1680569,195,8,1,9,4.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
80,276171,195,19,5,11,3.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
81,2744976,195,22,5,10,7.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
82,2781919,195,25,1,14,4.0,196,1,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
83,1738718,195,31,2,8,4.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
84,3058369,195,34,3,10,6.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
85,1485596,195,37,2,15,0.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
86,417035,195,40,3,16,2.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
87,1615297,195,47,5,10,2.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
88,1765587,195,52,3,12,2.0,196,3,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
89,745908,195,57,4,11,3.0,196,3,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730
90,2505656,222,17,2,12,1.0,196,2,0,195,Soda,77,7,9.0,both,70,Loyal customer,6.862397
91,3268370,222,38,5,15,1.0,196,6,1,195,Soda,77,7,9.0,both,70,Loyal customer,6.862397
92,2016711,290,9,5,19,6.0,196,8,0,195,Soda,77,7,9.0,both,51,Loyal customer,7.285597
93,2706088,290,28,6,10,7.0,196,16,1,195,Soda,77,7,9.0,both,51,Loyal customer,7.285597
94,1952286,331,6,5,16,30.0,196,8,0,195,Soda,77,7,9.0,both,8,New customer,7.705128
95,3226575,360,1,5,12,NaN,196,1,0,195,Soda,77,7,9.0,both,3,New customer,10.006250
96,1469869,377,3,5,17,3.0,196,9,0,195,Soda,77,7,9.0,both,3,New customer,8.496552
97,1927023,387,2,4,10,22.0,196,3,0,195,Soda,77,7,9.0,both,8,New customer,7.396610
98,858092,420,4,1,19,30.0,196,2,0,195,Soda,77,7,9.0,both,22,Regular customer,7.657813
99,119314,420,5,3,19,16.0,196,2,1,195,Soda,77,7,9.0,both,22,Regular customer,7.657813

In [28]:
# Create flags to assign "spending" labels to user ID based on mean product price
df.loc[df['mean_price'] < 10, 'spending_flag'] = 'Low spender'

In [29]:
df.loc[df['mean_price'] >= 10, 'spending_flag'] = 'High spender'

In [30]:
# Check frequencies of spending flags for accuracy
df['spending_flag'].value_counts(dropna = False)

Low spender     31798751
High spender      635461
Name: spending_flag, dtype: int64

##  Create order frequency flag that indicates users' ordering behavior

In [31]:
# Group data by "user_id" column, generate median product of "days since prior order, create "median_days" for aggregation results
df['median_days'] = df.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [32]:
# Check grouping
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0.1_y,product_name,aisle_id,department_id,prices,_merge,max_order,loyalty_flag,mean_price,spending_flag,median_days
0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,both,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,both,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,196,3,0,195,Soda,77,7,9.0,both,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,196,15,1,195,Soda,77,7,9.0,both,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,196,1,1,195,Soda,77,7,9.0,both,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,196,2,0,195,Soda,77,7,9.0,both,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,196,17,0,195,Soda,77,7,9.0,both,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,196,14,1,195,Soda,77,7,9.0,both,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,196,9,0,195,Soda,77,7,9.0,both,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,196,1,1,195,Soda,77,7,9.0,both,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,196,4,0,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
24,1318871,52,2,1,10,7.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
25,1261384,52,3,1,10,7.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
26,580568,52,5,2,10,8.0,196,6,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
27,2428073,52,7,2,7,8.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
28,342306,52,9,1,11,7.0,196,5,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
29,1520353,52,10,2,10,8.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
30,2542086,52,11,2,9,7.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
31,944694,52,12,1,16,6.0,196,7,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
32,1268191,52,15,2,11,8.0,196,3,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
33,1122089,52,17,2,10,6.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
34,1498922,52,18,2,10,14.0,196,6,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
35,180919,52,19,3,8,8.0,196,4,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
36,2695875,52,21,5,10,30.0,196,1,1,195,Soda,77,7,9.0,both,27,Regular customer,6.408876,Low spender,8.0
37,3205960,67,1,3,11,NaN,196,1,0,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,16,4,10,9.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,18,5,16,4.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,19,0,14,9.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,21,1,9,5.0,196,2,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,22,1,11,14.0,196,3,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,23,1,14,14.0,196,1,1,195,Soda,77,7,9.0,both,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,3,1,9,14.0,196,2,0,195,Soda,77,7,9.0,both,7,New customer,8.262963,Low spender,30.0
57,1812985,81,5,2,20,30.0,196,1,1,195,Soda,77,7,9.0,both,7,New customer,8.262963,Low spender,30.0
58,1889835,82,1,3,15,NaN,196,6,0,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,3,5,10,5.0,196,2,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
60,2728456,82,4,0,11,16.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
61,2653743,82,6,4,9,13.0,196,5,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
62,1358880,82,9,1,10,30.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
63,343588,82,10,2,11,1.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
64,3034663,82,15,2,11,12.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
65,147262,82,18,1,13,7.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
66,3144004,82,19,2,15,8.0,196,1,1,195,Soda,77,7,9.0,both,19,Regular customer,6.441221,Low spender,11.5
67,2126069,98,3,0,9,25.0,196,7,0,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
68,2210120,98,7,5,14,5.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
69,681011,98,9,3,9,30.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
70,2846344,98,11,4,13,15.0,196,2,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
71,747431,98,12,6,13,30.0,196,4,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
72,2383054,98,13,4,11,30.0,196,1,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
73,1993729,98,14,5,8,8.0,196,2,1,195,Soda,77,7,9.0,both,14,Regular customer,8.028000,Low spender,25.0
74,1403849,109,3,3,17,9.0,196,5,0,195,Soda,77,7,9.0,both,6,New customer,5.850725,Low spender,26.0
75,520620,120,1,3,11,NaN,196,2,0,195,Soda,77,7,9.0,both,3,New customer,9.385714,Low spender,19.0
76,3273029,120,3,2,8,19.0,196,2,1,195,Soda,77,7,9.0,both,3,New customer,9.385714,Low spender,19.0
77,1861943,185,2,1,12,25.0,196,10,0,195,Soda,77,7,9.0,both,6,New customer,7.715000,Low spender,25.0
78,2040988,195,1,1,14,NaN,196,2,0,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
79,1680569,195,8,1,9,4.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
80,276171,195,19,5,11,3.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
81,2744976,195,22,5,10,7.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
82,2781919,195,25,1,14,4.0,196,1,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
83,1738718,195,31,2,8,4.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
84,3058369,195,34,3,10,6.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
85,1485596,195,37,2,15,0.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
86,417035,195,40,3,16,2.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
87,1615297,195,47,5,10,2.0,196,2,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
88,1765587,195,52,3,12,2.0,196,3,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
89,745908,195,57,4,11,3.0,196,3,1,195,Soda,77,7,9.0,both,58,Loyal customer,7.149730,Low spender,4.0
90,2505656,222,17,2,12,1.0,196,2,0,195,Soda,77,7,9.0,both,70,Loyal customer,6.862397,Low spender,5.0
91,3268370,222,38,5,15,1.0,196,6,1,195,Soda,77,7,9.0,both,70,Loyal customer,6.862397,Low spender,5.0
92,2016711,290,9,5,19,6.0,196,8,0,195,Soda,77,7,9.0,both,51,Loyal customer,7.285597,Low spender,7.0
93,2706088,290,28,6,10,7.0,196,16,1,195,Soda,77,7,9.0,both,51,Loyal customer,7.285597,Low spender,7.0
94,1952286,331,6,5,16,30.0,196,8,0,195,Soda,77,7,9.0,both,8,New customer,7.705128,Low spender,30.0
95,3226575,360,1,5,12,NaN,196,1,0,195,Soda,77,7,9.0,both,3,New customer,10.006250,High spender,4.0
96,1469869,377,3,5,17,3.0,196,9,0,195,Soda,77,7,9.0,both,3,New customer,8.496552,Low spender,16.5
97,1927023,387,2,4,10,22.0,196,3,0,195,Soda,77,7,9.0,both,8,New customer,7.396610,Low spender,8.0
98,858092,420,4,1,19,30.0,196,2,0,195,Soda,77,7,9.0,both,22,Regular customer,7.657813,Low spender,7.0
99,119314,420,5,3,19,16.0,196,2,1,195,Soda,77,7,9.0,both,22,Regular customer,7.657813,Low spender,7.0

In [33]:
# Create flags to assign "freqency" labels to user ID based on median days since prior order
df.loc[df['median_days'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [34]:
df.loc[(df['median_days'] > 10) & (df['median_days'] <= 20), 'frequency_flag'] = 'Regular customer'

In [35]:
df.loc[df['median_days'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [36]:
# Check frequencies of spending flags for accuracy
df['frequency_flag'].value_counts(dropna=False)

Frequent customer        21577409
Regular customer          7217134
Non-frequent customer     3639669
Name: frequency_flag, dtype: int64

In [37]:
# Examining the null values
print(df[df.frequency_flag.isnull()])

Empty DataFrame
Columns: [order_id, user_id, order_number, orders_day_of_week, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, Unnamed: 0.1_y, product_name, aisle_id, department_id, prices, _merge, max_order, loyalty_flag, mean_price, spending_flag, median_days, frequency_flag]
Index: []

[0 rows x 21 columns]

In [38]:
# Changing the null values in "frequency_flag" column to "Non-frequent customer"
df['frequency_flag'].fillna("Non-frequent customer", inplace = True)

In [39]:
df['frequency_flag'].value_counts(dropna=False)

Frequent customer        21577409
Regular customer          7217134
Non-frequent customer     3639669
Name: frequency_flag, dtype: int64

In [41]:
# Export data to pkl
df.to_pickle(os.path.join(path, 'orders_products_aggregated.pkl'))